export const metadata = {
  title: 'Portfolio',
  description: 'Generated by PortfolioMaker',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
